# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b5b459c6272a3ab0d30591899c6ca64070c11f3cd46af1b658c5d85e970cf8eea68ea130d6f691afb877f1b4bb55466a47005f2c207af82d4f690a195e83ac3

test:
  secret_key_base: 7db7be0f87d21073d951d3a8103d2bef30be428e0d023971f2401b6973551ebb41c53408ad12de6f205ba62b864deb1ec654f099fc6c3321253d129a1f93c9d6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
